config/routes.rb
NominateTraining::Application.routes.draw do
  
  resources :employees
  resources :projects
  resources :skills
  
  get "nominate_trainee_details/new"
   match "/employee/show"=>"employee_trainings#show"  
  match "cancel" => "employee_trainings#cancel"
  match "trainings"=>"employee_trainings#trainings"
  match 'EmployeeTrainings' =>"EmployeeTrainings#index"
  get  'nominate' => "employee_trainings#nominate";
  match "search_nominee_employee_nomination"=>"employee_trainings#search_nominee_employee_nomination"
  
  root:to=>"EmployeeTrainings#index"
  
  match 'ManagerApproval' => "ManagerApproval#index"   
  match 'ManagerApproval/approve' => 'ManagerApproval#approve'
  match 'ManagerApproval/reject' => 'ManagerApproval#reject'

  match 'NominateTraining' => "NominateTraining#index" 
  match 'NominateTraining/create' => "NominateTraining#create" 
  match 'NominateTraining/cancel' => "NominateTraining#cancel"
  match 'NominateTraining/search' => "NominateTraining#search"

  match "employee_trainings" => "ManagerApproval#approve"
  
  
  match "search_nominee" => "nomineeDetails#search_nominee"

  match "search_nomineedata"=>"nomineeDetails#search_nomineedata"
  
   match "search_nominee_mail"=>"nomineeDetails#search_nominee_mail"
   match "search_nominee_summary"=>"nomineeDetails#search_nominee_summary"
  
  

end

app/models/employee_training.rb
class EmployeeTraining < ActiveRecord::Base
  belongs_to :employee
  belongs_to :training
  
  def self.get_employee_details
    @trainings = find_by_sql("SELECT emp_trn.id,emp_trn.employee_id,emp.emp_number,emp.employee_name,trn.training_name,trn.start_date,trn.end_date,trn.duration,trn.location,
    emp_trn.status,emp.project FROM employees emp,trainings trn,employee_trainings emp_trn
    WHERE emp.id=emp_trn.employee_id AND trn.id=emp_trn.training_id  AND STATUS=1;")
  end

  def self.update_employee_details(checkedid,status,comments)
    @trainings = EmployeeTraining.find(checkedid)
    @trainings.update_attributes(:status => status,:comments => comments)
    return true;
  end
  
  def self.get_email_data(checkedid)
    @email_datas=EmployeeTraining.find(checkedid)
  end
  
  def self.get_emp_email_data(training_id)
    @employee_emaildatas=EmployeeTraining.find_by_sql("SELECT * FROM employee_trainings WHERE training_id=13;")
  end
end

app/controllers/employee_trainings_controller.rb
class EmployeeTrainingsController < ApplicationController
  require 'date'
  require 'time'

  # GET /employee_trainings
  # GET /employee_trainings.json
  helper_method :sort_column
  
  def index
    @employee = Employee.find(1)
    @projects =Project.all
    @skills= Skill.all
    @employee_trainings = EmployeeTraining.all
    @trainings = Training.all
  end

  def search_nominee_employee_nomination
    skill = Skill.find(params[:skill_id])
    if params[:start_date]=="" && params[:end_date]==""
    @trainings = Training.find(:all,:conditions =>["training_name like ? ", "%#{skill.technologies}%"])
     elsif 
       @trainings = Training.find(:all,:conditions =>["training_name like ? and start_date >= ? ", "%#{skill.technologies}%",params[:start_date] ])
    elsif
     @trainings = Training.find(:all,:conditions =>["training_name like ? and start_date >= ? and end_date <= ? ", "%#{skill.technologies}%",params[:start_date], params[:end_date]])
    end
    respond_to do |format|
      format.html
    end
  end

  def nominate
    params[:employee_training_id].each do |training_id|
    @employee_training = EmployeeTraining.new(:training_id => training_id,:employee_id => 2,:status => 1) 
    @employee_training.save
    @employee_emaildatas=EmployeeTraining.get_emp_email_data(training_id)
    UserMailer.trn_nominated_email_byemp(@employee_emaildatas).deliver
    end
    flash.keep[:notice]="Your nomination request has send for Manager Review"
    redirect_to :controller=>'EmployeeTrainings',:action=>'index'
 
  end

  def cancel

    redirect_to :controller=>'EmployeeTrainings',:action=>'search_nominee_employee_nomination'
  end
  # StringBuffer b=new StringBuffer();
  # if(id!=null){
  #
  # b.append("where id?"+id);
  # }

  # GET /employee_trainings/1
  # GET /employee_trainings/1.json
  

end

app/views/employee_trainings/_form.html.erb
<%= form_for(@employee_training) do |f| %>
  <% if @employee_training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_training.errors.count, "error") %> prohibited this employee_training from being saved:</h2>

      <ul>
      <% @employee_training.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :training_id %><br />
    <%= f.number_field :training_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_trainings/edit.html.erb
<h1>Editing employee_training</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_training %> |
<%= link_to 'Back', employee_trainings_path %>

app/views/employee_trainings/index.html.erb
<html>
<head>
</head>


<title> Nominate Trainee Details</title>
<%- if !notice.nil? -%>
 
 <h2><p class="notice" align="center"><%= notice %></p></h2>
 
 <%- end -%> 
   <h2>Nominate Trainee Details </h2>
  	<%= form_for(@employee) do |i| %>
  	
    <table width="100%" border="0" cellpadding="4" cellspacing="1" class="tblBorder">
     <tr>
      <td width="20%"   class="tblLabel"><%= label(:employees, :name, "Employee Name", :class => "tblLabel") %>  </td>
      <td width="36%" class="tblContent"><%= text_field(:employees, :name, :class => "inputField ", :value => @employee.employee_name , :readonly =>"readonly" ) %></td>
      <td width="20%" class="tblLabel"><%= label(:projects, :project, "Project", :class => "tblLabel") %></td>
      <td width="30%" class="tblContent"><%= text_field(:employees, :name, :class => "inputField ", :value => @employee.project , :readonly =>"readonly" ) %></td>
      	
      </td>
    </tr>
      <td width="20%" class="tblLabel"><%= label(:employee, :id, "Employee Id", :class => "tblLabel") %></td>
      <td width="36%" class="tblContent" ><%= text_field(:employees, :emp_number, :class => "inputField", :value => @employee.emp_number, :readonly =>"readonly" ) %></td>
      <td width="20%" class="tblLabel"><%= label(:depts, :dept, "Email id", :class => "tblLabel") %></td>
      <td width="36%" class="tblContent" ><%= text_field(:employees, :empCode, :class => "inputField" , :value => @employee.email_id , :readonly =>"readonly") %></td>
      </table>
      <table width="100%" border="0" cellpadding="4" cellspacing="1" class="tblBorder">
      <tr>
        <td width="20%"   class="tblLabel" valign="top"> Skill</td>
        <td colspan="3" class="tblContent"><%= collection_select :skill,:id, @skills, :id, :technologies, {}, {:multiple => true}%></td>
      </tr>
      <tr>
        <td class="tblLabel">Start Date</td>
        <td><%= text_field :training, :start_date %></td>
        <td width="20%" class="tblLabel">End Date</td>
        <td><%= text_field :training, :end_date %></td>
      </tr>
    </table>
    <table>
    <tr>
    	
    	<td width="100%" align='right'></td><td align="right">
    	<td align="right"><%= submit_tag "Search", :type => 'button', :id =>"search_button", :class=> "buttonBlueLeft" %></td>
    		<td width="100%" align='right'></td><td align="right">
    
    	<td align="right"> <%= submit_tag "Reset", :type => 'button', :onClick => "resetdata();" , :class=> "buttonBlueLeft"%></td>
    	<td width="80%" align='right'></td><td align="right">
    	
    	   </tr>
    </table> 
   
  <% end %>
     
    <div id="result">
    </div>
    <tr>
      
</body>
 <script>
 
$('#search_button').click(function (){
var	skill_id =$('#skill_id').val();
var start_date =$('#training_start_date').val();
var end_date =$('#training_end_date').val();
       $.ajax({
          url: "search_nominee_employee_nomination",
          data: 'skill_id='+skill_id + '&start_date='+start_date + '&end_date='+end_date ,
          success: function(data){
		  $("#result").html(data);
		  }
	});
})
function resetdata(){
	$('#searchtoggling').hide();
	document.getElementById('training_start_date').value="";
	document.getElementById('training_end_date').value="";
	
}

$(document).ready(function () {
	
	 $("#training_start_date").datepicker({
			showOn: "button",
			buttonImage: "/images/date-picker.png",
			buttonImageOnly: true,
		    minDate: " "
			 
		});
	 $("#training_end_date").datepicker({
			showOn: "button",
			buttonImage: "/images/date-picker.png",
			buttonImageOnly: true,
			minDate: " "
		});
});

</script>
</html>	

app/views/employee_trainings/search_nominee_employee_nomination.html.erb
 <%= form_for(@trainings,:url => {:action =>"nominate"},:method =>"get") do |f|%>
 <div class="portletSkin" style="height:400px;" id="searchtoggling" display:none>
    <div class="portletHeader">Nominate Trainee Details</div>
    <div style="padding:10px;">
      <table width="100%" border="0" cellpadding="4" cellspacing="1" class="tblBorder">
        <tr class="thead">
          <td align="center"><input type="checkbox" name="chk5" id="chk5" />
          	
          </td>
          <td>Training ID</td>
          <td>Training Name</td>
          <td>Trainer Name</td>
          <td>Start Date</td>
          <td>End Date</td>
          <td>Duration</td>
        </tr>
       <% if (@trainings.length > 0) %> 
       	<% @trainings.each do |i| %>
          <tr class="tblRow1">
	         <td align="center"> <%= check_box_tag('employee_training_id[]',i.id) %></td>
	         <td><%= i.training_id %></td>
	         <td><%= i.training_name %></td>
	         <td><%= i.trainer_name %></td>
	         <td><%= i.start_date %></td>
	         <td><%= i.end_date %></td>
	         <td><%= i.duration %></td>
	        
         </tr>
        <%end%>
       <%end %>
</table>

   <div style="float:right;margin-top:5px;">
      <div style="cursor:pointer">
        <div ><%= submit_tag "Nominate",:class=> "buttonBlueLeft" %></div>
        <div></div>
      </div>
    </div>
    <%end%>

app/views/employee_trainings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Training:</b>
  <%= @employee_training.training_id %>
</p>

<p>
  <b>Employee:</b>
  <%= @employee_training.employee_id %>
</p>

<p>
  <b>Status:</b>
  <%= @employee_training.status %>
</p>


<%= link_to 'Edit', edit_employee_training_path(@employee_training) %> |
<%= link_to 'Back', employee_trainings_path %>